version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql-server
    image: mysql
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    #volumes:
    #  - './zabbix/mysql:/var/lib/data'
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=danillocampelo
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=alamo123
      
  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway
    networks:
      - network-zabbix
    restart: unless-stopped
  
  zabbix-server:
    container_name: zabbix-server-mysql
    image: zabbix/zabbix-server-mysql
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-java-gateway
    restart: unless-stopped
    ports:
      - '10051:10051'
    #volumes:
    #  - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=alamo123
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: unless-stopped
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=alamo123
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql
      
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: unless-stopped
    ports:
      - '3000:3000'
    #environment: 
    #  - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server
      
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent
    user: root
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    privileged: true
    #volumes:
    #  - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server

    
